### ISSUE TITLE
Use BinaryBuilder?

### ISSUE THREAD

**Issue by devmotion** [TuringLang/Torch.jl#2]
Maybe one can use [BinaryBuilder](https://github.com/JuliaPackaging/BinaryBuilder.jl) for building and deploying the PyTorch library?

**Comment by KDr2** [comment]
Now, binaries for Linux are built via BinarBuilder, for macOS are built via GitHub Action.

**Comment by devmotion** [comment]
For Julia >= 1.3, I'm wondering if it would be easier if the build scripts are added to [Yggdrasil](https://github.com/JuliaPackaging/Yggdrasil) so that the build process and release of the binaries is independent of the package release of Torch.jll? Then one could just add a dependency on Torch_jll here, and maybe that would make hickups such as the ones with the builds in Libtask less likely.

**Comment by KDr2** [comment]
libtorch can be compiled with BinaryBuilder's macOS SDK, I will follow up on the issue and move the build script to Yggdrasil when it can be compiled on the macOS SDK.
